"   Mouse Mid Mutton:             Show the menu.",
"   1                             Select 'Walk'  camera manipulator(default)",
"   2                             Select 'Drive' camera manipulator",
"   3                             Select 'Flight'camera manipulator",
"   4                             Show the weapon",
"   Walk w:                       move forward",
"   Walk s:                       move back",
"   Walk a:                       move left",
"   Walk d:                       move right",
"   Drive w:                      move forward",
"   Drive s:                      move back",
"   Drive a:                      turn left",
"   Drive d:                      turn right",
"   Flight w:                     turn down",
"   Flight s:                     turn up",
"   Flight a:                     head left",
"   Flight d:                     head right",
"   Flight q:                     rotate z axis negative",
"   Flight e:                     rotate z axis positive",
"   TrackBall LBtn:               rotate object",
"   TrackBall RBtn:               reset object ",
"   space                         reset the camera's position",
"   q                             change the animation type",
"   p                             play the music",
"   c                             change the mode of camera",
"   H TAB                         show the hlep list",
"   escap                         quit"
// 24 + 3